CREATE TABLE "RecoveryRequests" (
    "Id" SERIAL PRIMARY KEY,
    "RecoveryJobRequestId" INTEGER NOT NULL DEFAULT 0,
    "ClientId" VARCHAR(255) NOT NULL,
    "RequestAcknowledged" BOOLEAN NOT NULL DEFAULT FALSE,
    "Description" VARCHAR(2000),
    "LocationName" VARCHAR(200),
    "Address" VARCHAR(500),
    "AddressExt" VARCHAR(100),
    "City" VARCHAR(100),
    "StateId" INTEGER,
    "PostalCode" VARCHAR(20),
    "CountryId" INTEGER,
    "PrimaryContactFirstName" VARCHAR(100),
    "PrimaryContactLastName" VARCHAR(100),
    "SecondaryContactFirstName" VARCHAR(100),
    "SecondaryContactLastName" VARCHAR(100),
    "PrimaryContactCellPhoneNumber" VARCHAR(20),
    "SecondaryContactCellPhoneNumber" VARCHAR(20),
    "PrimaryContactEmailAddress" VARCHAR(255),
    "SecondaryContactEmailAddress" VARCHAR(255),
    "RequestedPickUpDate" TIMESTAMP,
    "RequestedPickUpTime" TIME,
    "CanSiteAccommodate53FeetTruck" BOOLEAN NOT NULL DEFAULT FALSE,
    "DoesSiteHaveADock" BOOLEAN NOT NULL DEFAULT FALSE,
    "CanHardwareBeResold" BOOLEAN NOT NULL DEFAULT FALSE,
    "CanHardDrivesBeResold" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsEquipmentLoose" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsEquipmentPalletized" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsLiftGateRequired" BOOLEAN NOT NULL DEFAULT FALSE,
    "IsOnsiteDataDestructingRequiredWipingShredding" BOOLEAN NOT NULL DEFAULT FALSE,
    "TypeOfMediaToBeDestroyed" VARCHAR(500),
    "OtherInstructions" VARCHAR(2000),
    "InstructionUpload" VARCHAR(500),
    "EquipmentListUpload" VARCHAR(500),
    "AssetsPhotoUpload1" VARCHAR(500),
    "AssetsPhotoUpload2" VARCHAR(500),
    "AssetsPhotoUpload3" VARCHAR(500),
    "AssetsPhotoUpload4" VARCHAR(500),
    "AssetsPhotoUpload5" VARCHAR(500),
    "HelpfulPhotoUpload1" VARCHAR(500),
    "HelpfulPhotoUpload2" VARCHAR(500),
    "HelpfulPhotoUpload3" VARCHAR(500),
    "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
    "DateClosed" TIMESTAMP,
    "ClosureComments" VARCHAR(2000),
    "DateCreated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DateUpdated" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CreatedBy" INTEGER NOT NULL,
    "UpdatedBy" INTEGER NOT NULL
);

CREATE INDEX "IX_RecoveryRequests_PrimaryContactFirstName_PrimaryContactLastName_ClientId" 
ON "RecoveryRequests" ("PrimaryContactFirstName", "PrimaryContactLastName", "ClientId");
